src/bestpricedflights/apps/core/urls.py
from django.urls import path

from bestpricedflights.apps.core.views import search_flights

from .views import DestinationListView, HomeView, TripListView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search/<str:origin>/<str:travel_class>/<str:trip_type>", search_flights),
    path("search/<str:origin>/<str:travel_class>/", search_flights),
    path("search/<str:origin>/", search_flights),
    path("list/destinations/<str:destination>", DestinationListView.as_view(), name="offers_by_destination_city"),
    path(
        "list/destinations/country/<str:destination_country>",
        DestinationListView.as_view(),
        name="offers_by_destination_country",
    ),
    path("list/trips/", TripListView.as_view(), name="trip_list"),
]

src/bestpricedflights/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bestpricedflights.apps.core.urls")),
    path("", include("bestpricedflights.apps.user.urls")),
    *debug_toolbar_urls(),
]

src/flightsearch/apps/core/urls.py
from django.urls import path

from flightsearch.apps.core.views import search_flights

from .views import DestinationListView, HomeView, TripListView

urlpatterns = [
    path("", HomeView.as_view()),
    path("search/<str:origin>/<str:travel_class>/<str:trip_type>", search_flights),
    path("search/<str:origin>/<str:travel_class>/", search_flights),
    path("search/<str:origin>/", search_flights),
    path("list/destinations/<str:destination>", DestinationListView.as_view(), name="offers_by_destination_city"),
    path(
        "list/destinations/country/<str:destination_country>",
        DestinationListView.as_view(),
        name="offers_by_destination_country",
    ),
    path("list/trips/", TripListView.as_view()),
]

src/flightsearch/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("flightsearch.apps.core.urls")),
    *debug_toolbar_urls(),
]

src/bestpricedflights/apps/core/models.py
import uuid

import structlog
from django.db import models
from djmoney.models.fields import MoneyField
from djmoney.money import Money

from .choices import Month, TravelClass, TripType

logger = structlog.getLogger(__name__)


class MoneyOutputField(MoneyField):
    def from_db_value(self, value, expression, connection):  # noqa: ARG002
        return Money(value, "EUR") if value else None


class Country(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name} ({self.code})"


class City(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255)
    region = models.CharField(max_length=255, blank=True)
    country = models.ForeignKey(Country, related_name="city", on_delete=models.SET_NULL, null=True, default=None)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    is_origin = models.BooleanField(default=False)
    is_destination = models.BooleanField(default=False)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name} ({self.code})"


class Trip(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fetched_on = models.DateField()
    origin = models.ForeignKey(City, related_name="flights_from", on_delete=models.CASCADE)
    destination = models.ForeignKey(City, related_name="flights_to", on_delete=models.CASCADE)
    travel_class = models.CharField(choices=TravelClass, default=TravelClass.BUSINESS)
    trip_type = models.CharField(choices=TripType, default=TripType.RETURN)

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=["origin", "destination", "travel_class", "trip_type"], name="unique_flight"
            ),
        )
        ordering = ("destination", "origin", "travel_class", "trip_type")

    def __str__(self):
        return f"{self.origin.code} – {self.destination.code} ({self.get_travel_class_display()})"  # noqa: RUF001


class Offer(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    month = models.IntegerField(choices=Month)
    price = MoneyField(max_digits=12, decimal_places=2, default_currency="EUR")
    stopovers = models.IntegerField(default=0)
    trip = models.ForeignKey(Trip, related_name="offers", on_delete=models.CASCADE)
    is_archived = models.BooleanField(default=False)
    price_in_eur = MoneyField(max_digits=12, decimal_places=2, default_currency="EUR", null=True)

    class Meta:
        ordering = ("trip", "price", "month")

    def __str__(self):
        return f"{self.trip}: {self.price} ({self.get_month_display()})"

src/bestpricedflights/apps/core/views.py
import structlog
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import F, Min, OuterRef, Prefetch, Q, Subquery
from django.http import JsonResponse
from django.views.generic import ListView, TemplateView
from tailslide import Median

from .lufthansa.destination_finder import TravelClass, TripType, find_destinations
from .models import City, Country, MoneyOutputField, Offer, Trip
from .tasks import fetch_and_store_destinations_task

logger = structlog.get_logger(__name__)


@login_required
def search_flights(request, origin, travel_class=TravelClass.BUSINESS.value, trip_type=TripType.RETURN.value):
    if not request.user.is_superuser:
        raise PermissionDenied

    response = find_destinations(origin, travel_class, trip_type)
    response.raise_for_status()

    fetch_and_store_destinations_task.delay(origin_code=origin)
    return JsonResponse(response.json())


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "destinations": City.objects.filter(is_destination=True).order_by("region", "country").distinct(),
            }
        )
        return context


class DestinationListView(LoginRequiredMixin, ListView):
    template_name = "destination_list.html"
    model = Offer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        destination_code = self.kwargs.get("destination")
        destination_country_code = self.kwargs.get("destination_country")
        destination = (
            City.objects.filter(code=destination_code).first()
            if destination_code
            else Country.objects.filter(code=destination_country_code).first()
            if destination_country_code
            else None
        )
        context.update({"destination": destination})
        return context

    def get_queryset(self):
        destination_code = self.kwargs.get("destination")
        destination_country_code = self.kwargs.get("destination_country")
        offer_filter = Q(is_archived=False)
        if destination_country_code:
            offer_filter &= Q(trip__destination__country__code=destination_country_code)
        elif destination_code:
            offer_filter &= Q(trip__destination__code=destination_code)

        # calculate median price over all entries with same destination in same month
        offers_by_destination_and_month = (
            Offer.objects.filter(
                month=OuterRef("month"),
                trip__destination__code=OuterRef("trip__destination__code"),
                trip__trip_type=OuterRef("trip__trip_type"),
                trip__travel_class=OuterRef("trip__travel_class"),
                price_in_eur__isnull=False,
            )
            .values("month", "trip__destination__code")
            .annotate(median_price=Median("price_in_eur", output_field=MoneyOutputField()))
        )

        return (
            Offer.objects.filter(offer_filter)
            .select_related("trip")
            .prefetch_related("trip__origin", "trip__destination", "trip__destination__country")
            .annotate(
                median=Subquery(offers_by_destination_and_month.values("median_price")[:1]),
            )
        )


class TripListView(LoginRequiredMixin, ListView):
    template_name = "trip_list.html"
    model = Trip

    def get_queryset(self):
        trips = Trip.objects.filter(offers__is_archived=False).distinct()

        best_price_offers = (
            Offer.objects.annotate(median=Median("trip__offers__price_in_eur", output_field=MoneyOutputField()))
            .filter(is_archived=False)
            .annotate(min_price=Min("trip__offers__price_in_eur"))
            .filter(price_in_eur=F("min_price"), price_in_eur__lte=F("median"))
        )

        return trips.select_related("origin", "destination", "destination__country").prefetch_related(
            Prefetch("offers", queryset=best_price_offers, to_attr="best_price_offers"),
        )

src/bestpricedflights/apps/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'vendor/data_tables/datatables-2.1.8.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-5.3.3-dist/css/bootstrap.css' %}"/>

    <script src="{% static 'vendor/jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'vendor/data_tables/datatables-2.1.8.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-5.3.3-dist/js/bootstrap.min.js' %}"></script>
    <script>
        addEventListener("DOMContentLoaded", () => {
            $('table.display').DataTable({
                displayLength: 25,
                initComplete: function () {
                    this.api()
                        .columns('.select')
                        .every(function () {
                            const column = this;

                            // Create select element and listener
                            const select = $('<select><option value=""></option></select>')
                                .appendTo($(column.footer()).empty())
                                .on('change', function () {
                                    column
                                        .search($(this).val(), {exact: true})
                                        .draw();
                                });

                            // Add list of options
                            column
                                .data()
                                .unique()
                                .sort()
                                .each(function (d, j) {
                                    select.append(
                                        '<option value="' + d + '">' + d + '</option>'
                                    );
                                });
                        });
                }
            });
        })
    </script>
</head>

<body>
<div id="content" class="container">
    <div class="d-flex justify-content-end gap-2 mt-2">
        {% block context_buttons %}
            <a class="btn btn-dark" href="{% url 'home' %}">Home Page</a>
            {% if user.is_authenticated %}
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-dark" href="{% url 'edit_profile' %}">Profile</a>
                    <button class="btn btn-dark mt-0" type="submit">Log Out</button>
                </form>
            {% else %}
                <a class="btn btn-dark" href="{% url 'login' %}">Log In</a>
            {% endif %}
        {% endblock %}
    </div>

    {% block content %}{% endblock %}
</div>
</body>
</html>

src/bestpricedflights/apps/core/templates/destination_list.html
{% extends "base.html" %}

{% block title %}Offer overview{% endblock %}

{% block content %}
    <h1>Offer overview for {{ destination }}</h1>
    <p>
        The Median is calculated based on the prices of all stored offers for the same destination city, month, travel class and trip type.
    </p>
    <table id="destination_list" class="display" data-order='[[3, "asc"], [5, "asc"]]'>
        <thead>
        <tr>
            <th class="select">Origin</th>
            <th class="select">Destination</th>
            <th class="select">Destination Country</th>
            <th>Price</th>
            <th>Median</th>
            <th class="select">Month</th>
            <th class="select">Stopovers</th>
            <th class="select">Travel Class</th>
            <th class="select">Trip Type</th>
        </tr>
        </thead>

        <tbody>
        {% for offer in object_list %}
            <tr>
                <td>{{ offer.trip.origin }}</td>
                <td>{{ offer.trip.destination }}</td>
                <td>{{ offer.trip.destination.country }}</td>
                <td data-order="{{ offer.price_in_eur.amount }}">{{ offer.price_in_eur }}</td>
                <td data-order="{{ offer.median.amount }}">{{ offer.median }}</td>
                <td data-order="{{ offer.month }}">{{ offer.get_month_display }}</td>
                <td>{{ offer.stopovers }}</td>
                <td>{{ offer.trip.get_travel_class_display }}</td>
                <td>{{ offer.trip.get_trip_type_display }}</td>
            </tr>
        {% endfor %}
        </tbody>

        <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </tfoot>
    </table>
{% endblock %}

src/bestpricedflights/apps/core/templates/home.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <h1>Home Page</h1>

    <h2>List of offers per region or country</h2>

    {% regroup destinations by region as region_list %}
    {% for region in region_list %}
        <h3>{{ region.grouper }}</h3>

        <div style="margin-left: 20px">
            {% regroup region.list by country as country_list %}
            {% for country in country_list %}
                <details>
                    <summary>
                        {% if country.grouper.code %}
                            <a href="{% url 'offers_by_destination_country' country.grouper.code %}">{{ country.grouper }}</a>
                        {% else %}
                            {{ country.grouper | default_if_none:'Unknown' }}
                        {% endif %}
                    </summary>
                    <ul>
                        {% for city in country.list %}
                            <li><a href="{% url 'offers_by_destination_city' city.code %}">{{ city }}</a></li>
                        {% endfor %}
                    </ul>
                </details>
            {% endfor %}
        </div>
    {% endfor %}



{% endblock %}

src/bestpricedflights/apps/core/templates/trip_list.html
{% extends "base.html" %}
{% load core_extras %}

{% block title %}Offer overview{% endblock %}

{% block content %}
    <h1>Best price offer overview</h1>
    <table id="trip_list" class="display" data-order='[[4, "asc"], [5, "asc"]]'>
        <thead>
        <tr>
            <th class="select">Origin</th>
            <th class="select">Destination</th>
            <th class="select">Destination Country</th>
            <th>Median</th>
            <th>Price</th>
            <th class="select">Month</th>
            <th class="select">Stopovers</th>
        </tr>
        </thead>
        <tbody>
        {% for trip in object_list %}
            {% for offer in trip.best_price_offers %}
                <tr>
                    <td>{{ trip.origin }}</td>
                    <td>{{ trip.destination }}</td>
                    <td>{{ trip.destination.country }}</td>
                    <td data-order="{{ offer.median.amount }}">{{ offer.median }}</td>
                    <td data-order="{{ offer.price_in_eur.amount }}">{{ offer.price_in_eur }}</td>
                    <td data-order="{{ offer.month }}">{{ offer.get_month_display }}</td>
                    <td>{{ offer.stopovers }}</td>
                </tr>
            {% endfor %}
        {% endfor %}
        </tbody>

        <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </tfoot>
    </table>
{% endblock %}